package app

var directNetworkClients = map[string]struct{}{
	"curl":  {},
	"wget":  {},
	"fetch": {},
}

type directClientFlagMode int

const (
	directClientFlagUnknown directClientFlagMode = iota
	directClientFlagNoValue
	directClientFlagTakesValue
	directClientFlagDestination
	directClientFlagOpaqueOrOverrideValue
)

type directClientArgSpec struct {
	longFlags  map[string]directClientFlagMode
	shortFlags map[byte]directClientFlagMode
}

var directClientArgSpecs = map[string]directClientArgSpec{
	"curl": {
		longFlags: map[string]directClientFlagMode{
			"--cacert":             directClientFlagTakesValue,
			"--capath":             directClientFlagTakesValue,
			"--cert":               directClientFlagTakesValue,
			"--compressed":         directClientFlagNoValue,
			"--config":             directClientFlagOpaqueOrOverrideValue,
			"--connect-timeout":    directClientFlagTakesValue,
			"--connect-to":         directClientFlagOpaqueOrOverrideValue,
			"--cookie":             directClientFlagTakesValue,
			"--cookie-jar":         directClientFlagTakesValue,
			"--data":               directClientFlagTakesValue,
			"--data-binary":        directClientFlagTakesValue,
			"--data-raw":           directClientFlagTakesValue,
			"--data-urlencode":     directClientFlagTakesValue,
			"--dump-header":        directClientFlagTakesValue,
			"--etag-compare":       directClientFlagTakesValue,
			"--etag-save":          directClientFlagTakesValue,
			"--fail":               directClientFlagNoValue,
			"--form":               directClientFlagTakesValue,
			"--form-string":        directClientFlagTakesValue,
			"--globoff":            directClientFlagNoValue,
			"--head":               directClientFlagNoValue,
			"--header":             directClientFlagTakesValue,
			"--http1.1":            directClientFlagNoValue,
			"--http2":              directClientFlagNoValue,
			"--http3":              directClientFlagNoValue,
			"--include":            directClientFlagNoValue,
			"--insecure":           directClientFlagNoValue,
			"--interface":          directClientFlagTakesValue,
			"--ipv4":               directClientFlagNoValue,
			"--ipv6":               directClientFlagNoValue,
			"--json":               directClientFlagTakesValue,
			"--key":                directClientFlagTakesValue,
			"--limit-rate":         directClientFlagTakesValue,
			"--location":           directClientFlagNoValue,
			"--mail-from":          directClientFlagTakesValue,
			"--mail-rcpt":          directClientFlagTakesValue,
			"--max-time":           directClientFlagTakesValue,
			"--next":               directClientFlagNoValue,
			"--noproxy":            directClientFlagTakesValue,
			"--output":             directClientFlagTakesValue,
			"--output-dir":         directClientFlagTakesValue,
			"--preproxy":           directClientFlagOpaqueOrOverrideValue,
			"--progress-bar":       directClientFlagNoValue,
			"--proxy":              directClientFlagOpaqueOrOverrideValue,
			"--proxy1.0":           directClientFlagOpaqueOrOverrideValue,
			"--proxy-cacert":       directClientFlagTakesValue,
			"--proxy-cert":         directClientFlagTakesValue,
			"--proxy-key":          directClientFlagTakesValue,
			"--proxy-user":         directClientFlagTakesValue,
			"--range":              directClientFlagTakesValue,
			"--referer":            directClientFlagTakesValue,
			"--remote-header-name": directClientFlagNoValue,
			"--remote-name":        directClientFlagNoValue,
			"--request":            directClientFlagTakesValue,
			"--request-target":     directClientFlagTakesValue,
			"--resolve":            directClientFlagOpaqueOrOverrideValue,
			"--retry":              directClientFlagTakesValue,
			"--retry-delay":        directClientFlagTakesValue,
			"--retry-max-time":     directClientFlagTakesValue,
			"--show-error":         directClientFlagNoValue,
			"--silent":             directClientFlagNoValue,
			"--socks4":             directClientFlagOpaqueOrOverrideValue,
			"--socks4a":            directClientFlagOpaqueOrOverrideValue,
			"--socks5":             directClientFlagOpaqueOrOverrideValue,
			"--socks5-hostname":    directClientFlagOpaqueOrOverrideValue,
			"--ssl-reqd":           directClientFlagNoValue,
			"--unix-socket":        directClientFlagTakesValue,
			"--url":                directClientFlagDestination,
			"--url-query":          directClientFlagTakesValue,
			"--user":               directClientFlagTakesValue,
			"--user-agent":         directClientFlagTakesValue,
			"--verbose":            directClientFlagNoValue,
			"--write-out":          directClientFlagTakesValue,
		},
		shortFlags: map[byte]directClientFlagMode{
			'4': directClientFlagNoValue,
			'6': directClientFlagNoValue,
			'A': directClientFlagTakesValue,
			'D': directClientFlagTakesValue,
			'E': directClientFlagTakesValue,
			'F': directClientFlagTakesValue,
			'G': directClientFlagNoValue,
			'H': directClientFlagTakesValue,
			'I': directClientFlagNoValue,
			'J': directClientFlagNoValue,
			'K': directClientFlagOpaqueOrOverrideValue,
			'L': directClientFlagNoValue,
			'N': directClientFlagNoValue,
			'O': directClientFlagNoValue,
			'S': directClientFlagNoValue,
			'T': directClientFlagTakesValue,
			'X': directClientFlagTakesValue,
			'b': directClientFlagTakesValue,
			'c': directClientFlagTakesValue,
			'd': directClientFlagTakesValue,
			'e': directClientFlagTakesValue,
			'f': directClientFlagNoValue,
			'g': directClientFlagNoValue,
			'i': directClientFlagNoValue,
			'k': directClientFlagNoValue,
			'l': directClientFlagNoValue,
			'm': directClientFlagTakesValue,
			'o': directClientFlagTakesValue,
			'r': directClientFlagTakesValue,
			's': directClientFlagNoValue,
			'u': directClientFlagTakesValue,
			'v': directClientFlagNoValue,
			'w': directClientFlagTakesValue,
			'x': directClientFlagOpaqueOrOverrideValue,
			'y': directClientFlagTakesValue,
			'z': directClientFlagTakesValue,
		},
	},
	"wget": {
		longFlags: map[string]directClientFlagMode{
			"--accept":           directClientFlagTakesValue,
			"--bind-address":     directClientFlagTakesValue,
			"--body-data":        directClientFlagTakesValue,
			"--body-file":        directClientFlagTakesValue,
			"--ca-certificate":   directClientFlagTakesValue,
			"--certificate":      directClientFlagTakesValue,
			"--config":           directClientFlagOpaqueOrOverrideValue,
			"--connect-timeout":  directClientFlagTakesValue,
			"--continue":         directClientFlagNoValue,
			"--debug":            directClientFlagNoValue,
			"--directory-prefix": directClientFlagTakesValue,
			"--dns-timeout":      directClientFlagTakesValue,
			"--domains":          directClientFlagTakesValue,
			"--exclude-domains":  directClientFlagTakesValue,
			"--execute":          directClientFlagOpaqueOrOverrideValue,
			"--header":           directClientFlagTakesValue,
			"--help":             directClientFlagNoValue,
			"--inet4-only":       directClientFlagNoValue,
			"--inet6-only":       directClientFlagNoValue,
			"--input-file":       directClientFlagOpaqueOrOverrideValue,
			"--limit-rate":       directClientFlagTakesValue,
			"--load-cookies":     directClientFlagTakesValue,
			"--method":           directClientFlagTakesValue,
			"--mirror":           directClientFlagNoValue,
			"--no-verbose":       directClientFlagNoValue,
			"--output-document":  directClientFlagTakesValue,
			"--output-file":      directClientFlagTakesValue,
			"--password":         directClientFlagTakesValue,
			"--post-data":        directClientFlagTakesValue,
			"--post-file":        directClientFlagTakesValue,
			"--private-key":      directClientFlagTakesValue,
			"--quiet":            directClientFlagNoValue,
			"--read-timeout":     directClientFlagTakesValue,
			"--recursive":        directClientFlagNoValue,
			"--referer":          directClientFlagTakesValue,
			"--reject":           directClientFlagTakesValue,
			"--save-cookies":     directClientFlagTakesValue,
			"--server-response":  directClientFlagNoValue,
			"--spider":           directClientFlagNoValue,
			"--timeout":          directClientFlagTakesValue,
			"--timestamping":     directClientFlagNoValue,
			"--tries":            directClientFlagTakesValue,
			"--user":             directClientFlagTakesValue,
			"--user-agent":       directClientFlagTakesValue,
			"--verbose":          directClientFlagNoValue,
		},
		shortFlags: map[byte]directClientFlagMode{
			'4': directClientFlagNoValue,
			'6': directClientFlagNoValue,
			'A': directClientFlagTakesValue,
			'B': directClientFlagTakesValue,
			'D': directClientFlagTakesValue,
			'I': directClientFlagTakesValue,
			'N': directClientFlagNoValue,
			'O': directClientFlagTakesValue,
			'P': directClientFlagTakesValue,
			'Q': directClientFlagTakesValue,
			'S': directClientFlagNoValue,
			'T': directClientFlagTakesValue,
			'U': directClientFlagTakesValue,
			'Y': directClientFlagTakesValue,
			'a': directClientFlagTakesValue,
			'c': directClientFlagNoValue,
			'd': directClientFlagNoValue,
			'e': directClientFlagOpaqueOrOverrideValue,
			'h': directClientFlagNoValue,
			'i': directClientFlagOpaqueOrOverrideValue,
			'm': directClientFlagNoValue,
			'n': directClientFlagNoValue,
			'o': directClientFlagTakesValue,
			'q': directClientFlagNoValue,
			'r': directClientFlagNoValue,
			's': directClientFlagNoValue,
			't': directClientFlagTakesValue,
			'v': directClientFlagNoValue,
			'w': directClientFlagTakesValue,
		},
	},
	"fetch": {
		longFlags: map[string]directClientFlagMode{
			"--help": directClientFlagNoValue,
		},
		shortFlags: map[byte]directClientFlagMode{
			'A': directClientFlagTakesValue,
			'T': directClientFlagTakesValue,
			'a': directClientFlagTakesValue,
			'h': directClientFlagNoValue,
			'm': directClientFlagNoValue,
			'n': directClientFlagNoValue,
			'o': directClientFlagTakesValue,
			'v': directClientFlagNoValue,
		},
	},
}
